// Generated by Wrangler on Sun Sep 08 2024 23:24:53 GMT-0600 (Mountain Daylight Time)
// by running `wrangler types`

interface Env {
	BGG_BASE_URL: "https://boardgamegeek.com";
	THROTTLE_RATE_MS: 5000;
	MAX_ADD_GEEKPLAY_REQUESTS: 40;
	BGG_SOURCE_USERNAME: string;
	BGG_DESTINATION_USERNAME: string;
	BGG_DESTINATION_PASSWORD: string;
}
